openapi: 3.0.1
info:
  title: BaseWebAPI
  description: <script>alert('XSS from info')</script>
  version: v1
servers:
  - url: /api
paths:
  /api/Account/CheckLogin:
    post:
      tags:
        - Account
      summary: 檢查登入
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckLoginParameters'
          text/json:
            schema:
              $ref: '#/components/schemas/CheckLoginParameters'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CheckLoginParameters'
      responses:
        '200':
          description: OK<script>alert('XSS from 200')</script>
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckLoginParameters'
              example:
                message: <script>alert('XSS from response')</script>
components:
  schemas:
    CheckLoginParameters:
      type: object
      properties:
        username:
          type: string
          example: admin
        password:
          type: string
          example: '123456'
    ProblemDetails:
      type: object
      properties:
        detail:
          type: string
          example: Invalid input
